# Generated by Django 5.2.6 on 2025-09-07 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('telegram', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('gaming', 'Gaming'), ('study', 'Study Groups'), ('social', 'Social'), ('entertainment', 'Entertainment'), ('outdoor', 'Outdoor'), ('food', 'Food & Drinks'), ('arts', 'Arts & Culture'), ('fitness', 'Fitness & Wellness'), ('tech', 'Technology')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_attendees', models.PositiveIntegerField(default=50)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_balance', models.CharField(default='any', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('approval', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=10)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
